# Generated by Django 3.1.3 on 2020-12-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_app', '0008_productpart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesPerson',
            new_name='Agent',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sales_personid',
            new_name='agentid',
        ),
    ]
